Raise warning in pipeline if code is not formatted according to editorconfig

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -15,6 +15,22 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: 8.0.x
+      - name: Restore dependencies
+        run: dotnet restore
+      - name: Format
+        run: |
+          set +e  # Allow the next command to fail without stopping the workflow
+          dotnet format --verify-no-changes --verbosity diagnostic
+          STATUS=$?
+          if [ $STATUS -ne 0 ]; then
+            echo "::warning::Dotnet format verification failed"
+          fi
+          set -e  # Restore the default behavior
+        shell: bash  
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v1
         with:
